config/routes.rb
Rails.application.routes.draw do
  resources :depts
  resources :degrees

end

app/models/degree.rb
class Degree < ActiveRecord::Base
end

app/models/dept.rb
class Dept < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :set_degree, only: [:show, :edit, :update, :destroy]

  # GET /degrees
  # GET /degrees.json
  def index
    @dept_name = params[:dept_name]
    @dept = params[:dept]
    @degrees = Degree.all
    #response = RestClient.get 'http://jsonplaceholder.typicode.com/posts'
    #response = RestClient.get 'https://api.myjson.com/bins/1rlz1'
    #response = RestClient.get 'https://api.myjson.com/bins/3l4rz'
    response = RestClient.get @dept_name
    @parsed = JSON.parse(response)
    a=Array.new
    post=Array.new
    url=Array.new
    @b=Array.new
    count=0
    max_requirements=0
    no_of_terms=@parsed['terms'].size
    for k in 0..no_of_terms-1
    	count =@parsed['terms'][k]['requirements'].size 
    	if max_requirements < count
        	max_requirements= count
    	end
    end        

    for i in 0..no_of_terms-1
      for j in 0..@parsed['terms'][i]['requirements'].size-1
		  if @parsed['terms'][i]['requirements'][j]['courses'].size >=1        
			for k in 0..@parsed['terms'][i]['requirements'][j]['courses'].size-1
	          a<< [@parsed['terms'][i]['requirements'][j]['courses'][k]['number'],@parsed['terms'][i]['requirements'][j]['courses'][k]['title'],@parsed['terms'][i]['requirements'][j]['courses'][k]['prerequisites'],@parsed['terms'][i]['requirements'][j]['courses'][k]['postrequisites'],@parsed['terms'][i]['requirements'][j]['courses'][k]['url']]
			      
      end
		  else
	        a<< [['Req'],@parsed['terms'][i]['requirements'][j]['name'],['']]
		  end
      	     
	end	
    	@b.insert(i,a)
      a=Array.new

    end
  end

  # GET /degrees/1
  # GET /degrees/1.json
  def show
  end

  # GET /degrees/new
  def new
    @degree = Degree.new
  end

  # GET /degrees/1/edit
  def edit
  end

  # POST /degrees
  # POST /degrees.json
  def create
    @degree = Degree.new(degree_params)

    respond_to do |format|
      if @degree.save
        format.html { redirect_to @degree, notice: 'Degree was successfully created.' }
        format.json { render :show, status: :created, location: @degree }
      else
        format.html { render :new }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degrees/1
  # PATCH/PUT /degrees/1.json
  def update
    respond_to do |format|
      if @degree.update(degree_params)
        format.html { redirect_to @degree, notice: 'Degree was successfully updated.' }
        format.json { render :show, status: :ok, location: @degree }
      else
        format.html { render :edit }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degrees/1
  # DELETE /degrees/1.json
  def destroy
    @degree.destroy
    respond_to do |format|
      format.html { redirect_to degrees_url, notice: 'Degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree
      @degree = Degree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_params
      params[:degree]
    end
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  before_action :set_dept, only: [:show, :edit, :update, :destroy]

  # GET /depts
  # GET /depts.json
  def index
    @depts = Dept.all
    #response_dept = RestClient.get 'https://api.myjson.com/bins/4k8l7'
    #response_dept = RestClient.get 'https://api.myjson.com/bins/3l4rz'
    response_dept = RestClient.get 'https://api.myjson.com/bins/21r6t'
    @parsed_dept = JSON.parse(response_dept)
  end

  # GET /depts/1  
  # GET /depts/1.json
  def show
  end

  # GET /depts/new
  def new
    @dept = Dept.new
  end

  # GET /depts/1/edit
  def edit
  end

  # POST /depts
  # POST /depts.json
  def create
    @dept = Dept.new(dept_params)

    respond_to do |format|
      if @dept.save
        format.html { redirect_to @dept, notice: 'Dept was successfully created.' }
        format.json { render :show, status: :created, location: @dept }
      else
        format.html { render :new }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /depts/1
  # PATCH/PUT /depts/1.json
  def update
    respond_to do |format|
      if @dept.update(dept_params)
        format.html { redirect_to @dept, notice: 'Dept was successfully updated.' }
        format.json { render :show, status: :ok, location: @dept }
      else
        format.html { render :edit }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depts/1
  # DELETE /depts/1.json
  def destroy
    @dept.destroy
    respond_to do |format|
      format.html { redirect_to depts_url, notice: 'Dept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dept
      @dept = Dept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dept_params
      params[:dept]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/views/degrees/_form.html.erb
<%= form_for(@degree) do |f| %>
  <% if @degree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@degree.errors.count, "error") %> prohibited this degree from being saved:</h2>

      <ul>
      <% @degree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degrees/edit.html.erb
<h1>Editing Degree</h1>

<%= render 'form' %>

<%= link_to 'Show', @degree %> |
<%= link_to 'Back', degrees_path %>

app/views/degrees/index.html.erb
<!DOCTYPE html SYSTEM "about:legacy-compat">
<html lang="en">
   <head>
      <meta charset="utf-8"/>
      <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
      <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
      <meta content="suDeBu3cQ5JEfYn92UdyZqkDPVCRI3QFK4dbV1tzUNk" name="google-site-verification"/>
      <link href="//webcore.unm.edu/v1/images/unm.ico" rel="shortcut icon"/>
      <link href="//webcore.unm.edu/v2/css/unm-styles.min.css" rel="stylesheet"/>
      <link href="assets/css/site-styles.css" media="screen" rel="stylesheet" type="text/css"/>


   </head>
   <body id="home">
      <div id="page">
         <div id="upper">
           <div class="container">
            <br />
              <br />
                <br />

<br />

<div id="table-background">
<h3><center>Degree Plan of <%= @dept %></center></h3><br />


    <div>
      <center>
    <table border="0">
      <tbody id="courseTable">
        <tr class="class">
          <th colspan="2">Freshman</th>
          <th colspan="2">Sophomore</th>
          <th colspan="2">Junior</th>
          <th colspan="2" class="last">Senior</th>
        </tr>
        <tr class="semester">
          <th>Fall</th>
          <th>Spring</th>
          <th>Fall</th>
          <th>Spring</th>
          <th>Fall</th>
          <th>Spring</th>
          <th>Fall</th>
          <th class="last">Spring</th>
        </tr>
        <tr>
    <%for i in 0..@b.size-1 %>
        <td id = "term <%= i+1 %>"> 
    <%for j in 0..@b[i].size-1 %>
     <%if @b[i][j][0]!=['Req']%>

      <%prestr=""%>     
        <%@b[i][j][2].each do |pre|%>
      <%prestr << pre.to_s %>
      <%prestr << "~" %>
        <%end %> 

         <%poststr=""%>     
        <%@b[i][j][3].each do |post|%>
      <%poststr << post.to_s %>
      <%poststr<< "~" %>
        <%end %>         
    <div id="<%= @b[i][j][0]%>" pre="<%=prestr%>" post="<%=poststr%>" onclick="location.href='<%= @b[i][j][4] %>';"><%= @b[i][j][0]%>
      <!--<a href="<%= @b[i][j][4] %>"></a>-->
      <br>
      <span class="crs_title"><%= @b[i][j][1]%></span>
    </div>
	<%else%>
    <div><%= @b[i][j][1]%></div>
    <%end %>
    <% end %>
    </td>
    <% end %> 
    </tr>

<%= javascript_tag do %>
function highlightPrereq(element, index, array)
{
	$("div[id='"+element+"']").css("background-color", "#FFB266");
}

function highlightPostreq(element, index, array)
{
	$("div[id='"+element+"']").css("background-color", "#7DDB95");
}

function highlightCurrent()
{
	$("#courseTable div:hover").css("background-color", "#C8E6F6");
}

function clearTable() {
	$("#courseTable div").css("background-color", "#E2EDF3");
}

$("#courseTable div").mouseover(function() {
	var prereq = $(this).attr("pre");
	var postreq = $(this).attr("post");
	var prearr = prereq.split('~');
	var postarr = postreq.split('~');
	clearTable();
	highlightCurrent();
	prearr.forEach(highlightPrereq);
	postarr.forEach(highlightPostreq);
});

<% end %>
	
	
</tbody>
</table>
<br/>
<p id="legend" style="font-size: 50 px;line-height: 2em">Place the mouse over a course to highlight the <span style="background-color: #FFB266; border: 1px solid #555; color:#555; padding: 3px;">course prerequisites</span> and <span style="background-color: #7ddb95; border: 1px solid #555; padding: 3px; color:#555;">course postrequisites</span>.</p>
<p id = "legend"> Click on any course to view the course description.</p>
</center>
<br/>

</div> 
</div>
</div>
</div>
 <br />        
<br />
<br />
<br />
        

   </body>
</html>

app/views/degrees/new.html.erb
<h1>New Degree</h1>

<%= render 'form' %>

<%= link_to 'Back', degrees_path %>

app/views/degrees/show.html.erb
<p id="notice"><%= notice %></p>
<%= @dept_name %>
<%= link_to 'Edit', edit_degree_path(@degree) %> |
<%= link_to 'Back', degrees_path %>

app/views/depts/_form.html.erb
<%= form_for(@dept) do |f| %>
  <% if @dept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dept.errors.count, "error") %> prohibited this dept from being saved:</h2>

      <ul>
      <% @dept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/depts/edit.html.erb
<h1>Editing Dept</h1>

<%= render 'form' %>

<%= link_to 'Show', @dept %> |
<%= link_to 'Back', depts_path %>

app/views/depts/index.html.erb
<!DOCTYPE html SYSTEM "about:legacy-compat">
<html lang="en">
   <head>
      <meta charset="utf-8"/>
      <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
      <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
      <meta content="suDeBu3cQ5JEfYn92UdyZqkDPVCRI3QFK4dbV1tzUNk" name="google-site-verification"/>
      <link href="//webcore.unm.edu/v1/images/unm.ico" rel="shortcut icon"/>
      <link href="//webcore.unm.edu/v2/css/unm-styles.min.css" rel="stylesheet"/>
    
      <!-- bootstrap-carousal-->
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

   </head>
   <body id="home">

   <div id="page">



    <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="<%=asset_path('p3.jpg')%>"  alt ="p1"width="460" height="345">
      </div>
      <div class="item">
        <img src="<%=asset_path('p7.png')%>"  alt ="p2"width="460" height="345">
      </div>
      <div class="item">
        <img src="<%=asset_path('p5.jpg')%>" alt ="p3" width="460" height="345">
      </div>
      <div class="item">
        <img src="<%=asset_path('p4.png')%>" alt ="p4" width="460" height="345">
      </div>
    </div>
      <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="icon-prev" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="icon-next" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>


  </div>
         <div id="upper">
           <div class="container">
            <br />
            <br />
            <div class="jumbotron">
            <h2 > UNM Degree Plans</h2>

            <h3 style="color:#c10037;"><center>Welcome to UNM's Online Degree Plan Viewer</center></h3>
   Degree Plan Viewer is an Interactive web application which provides students a semester-by-semster outline of courses within a curriculum in a tabular format. Application allows the students and advisors to visualize pre- and post-requisites associated with a course. This application helps the students to understand how courses within a curriculum are liked and provides guiance for course scheduling.
   <br />
   <br />
   Whether you are a prospective student or enrolled at UNM, you will find we have provided you with a powerful tool to help you quickly locate and track details for undergraduate programs and courses that are important to you.
   <br />
   <br />
<h3> Programs Offered </h3>

   <div>
    <% @parsed_dept.each do |event| %>
      <% dept_name = event["url"] %>
      <% dept = event["name"] %>
       <li><%= link_to(event["name"], degrees_path(:dept_name => dept_name,:dept => dept)) %></li>
    <% end %>
   </div>
</div>

 </div>
</div>
   </body>
</html>

app/views/depts/new.html.erb
<h1>New Dept</h1>

<%= render 'form' %>

<%= link_to 'Back', depts_path %>

app/views/depts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dept_path(@dept) %> |
<%= link_to 'Back', depts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title> 
        UNM Degree Plan Viewer | The University of New Mexico 
 </title>
 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- old header -->

	<!--<div id="header">
		<div id="headerwrap" >
			<a href="http://www.unm.edu/"><img alt="UNM Logo" height="40px" src="http://degrees.unm.edu/assets/layout/Logo-072057a2d0687e68145f541da12b18e3.png"></a>
		</div>
	</div>

-->


<!-- new header-->

<div class="navbar navbar-unm">
            <div class="container">
               <a class="navbar-brand" href="http://www.unm.edu">The University of New Mexico</a><!-- search form -->
               
               <!-- end search form -->
               <ul class="nav navbar-nav navbar-right hidden-xs" id="toolbar-nav">
                  <li><a href="http://directory.unm.edu/departments/" title="UNM A to Z">UNM A-Z</a></li>
                  <li><a href="https://my.unm.edu" title="myUNM">myUNM</a></li>
                  <li><a href="http://directory.unm.edu" title="Directory">Directory</a></li>
                  <li class="dropdown">
                     <a class="dropdown-toggle" data-toggle="dropdown" href="#">Help <span class="caret"></span></a>
                     <ul class="dropdown-menu">
                        <li><a href="http://studentinfo.unm.edu" title="StudentInfo">StudentInfo</a></li>
                        <li><a href="http://fastinfo.unm.edu" title="FastInfo">FastInfo</a></li>
                     </ul>
                  </li>
               </ul>
            </div>
         </div>




<%= yield %>
<br />
<br />





   <div id="footer">
            <div class="container">
               <hr/>
               <div class="row">
                  <div class="col-md-8">
                     <p><a href="http://www.unm.edu"><img alt="The University of New Mexico" src="https://webcore.unm.edu/v2/images/unm-transparent-white.png"/></a></p>
                     <p><small>&#169; The University of New Mexico<br/>
                        Albuquerque, NM 87131, (505) 277-0111<br/>
                        New Mexico's Flagship University</small>
                     </p>
                  </div>
                  <div class="col-md-4">
                     <ul class="list-inline">
                        <li><a href="https://www.facebook.com/universityofnewmexico" title="UNM on Facebook"><span class="fa fa-facebook-square fa-2x">&#160;</span></a></li>
                        <li><a href="http://instagram.com/uofnm" title="UNM on Instagram"><span class="fa fa-instagram fa-2x">&#160;</span></a></li>
                        <li><a href="https://twitter.com/unm" title="UNM on Twitter"><span class="fa fa-twitter-square fa-2x">&#160;</span></a></li>
                        <li><a href="http://uofnm.tumblr.com" title="UNM on Tumblr"><span class="fa fa-tumblr-square fa-2x">&#160;</span></a></li>
                        <li><a href="http://www.youtube.com/user/unmlive" title="UNM on YouTube"><span class="fa fa-youtube-square fa-2x">&#160;</span></a></li>
                     </ul>
                     <p>more at <a href="http://social.unm.edu" title="UNM Social Media Directory &amp; Information">social.unm.edu</a></p>
                     <ul class="list-inline" id="unm_footer_links">
                        <li><a href="http://www.unm.edu/accessibility.html">Accessibility</a></li>
                        <li><a href="http://www.unm.edu/legal.html">Legal</a></li>
                        <li><a href="http://www.unm.edu/contactunm.html">Contact UNM</a></li>
                        <li><a href="http://nmhedss2.state.nm.us/Dashboard/index.aspx?ID=21">New Mexico Higher Education Dashboard</a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
</body>
</html>